-- Table: genesys.sensor_readings

-- DROP TABLE IF EXISTS genesys.sensor_readings;

CREATE TABLE IF NOT EXISTS genesys.sensor_readings
(
    reading_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    sensor_id bigint,
    temperature numeric NOT NULL,
    feels_like numeric NOT NULL,
    humidity_percent numeric NOT NULL,
    wind numeric NOT NULL,
    speed numeric NOT NULL,
    quality numeric NOT NULL,
    visibility numeric NOT NULL,
    pressure numeric NOT NULL,
    read_date timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT sensor_readings_pkey PRIMARY KEY (reading_id),
    CONSTRAINT fk_senor_readings FOREIGN KEY (sensor_id)
        REFERENCES genesys.sensor (sensor_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

    TABLESPACE pg_default;

ALTER TABLE IF EXISTS genesys.sensor_readings
    OWNER to postgres;