-- Table: genesys.sensor

-- DROP TABLE IF EXISTS genesys.sensor;

CREATE TABLE IF NOT EXISTS genesys.sensor
(
    sensor_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    description character varying(255) COLLATE pg_catalog."default" NOT NULL,
    model character varying(16) COLLATE pg_catalog."default" NOT NULL,
    brand character varying(16) COLLATE pg_catalog."default" NOT NULL,
    country character varying(16) COLLATE pg_catalog."default" NOT NULL,
    city character varying(16) COLLATE pg_catalog."default" NOT NULL,
    region character varying(16) COLLATE pg_catalog."default" NOT NULL,
    active "char" NOT NULL,
    CONSTRAINT sensor_pkey PRIMARY KEY (sensor_id)
)

    TABLESPACE pg_default;

ALTER TABLE IF EXISTS genesys.sensor
    OWNER to postgres;